### PR TITLE
Update to fluid_v3 in order to make it compile on linux

### PR DESCRIPTION
**Pull request by sergemartin**
Hello erwin

Please consider merging those change in order to make fluid v3 working on linux

Best regards

### CODE REVIEW

**Comment by cg-Kdaf** [comment]
Hello, any news about that ?

**Comment by erwincoumans** [comment]
Haven't touched this for 7 years, let's merge it.

**Comment by cg-Kdaf** [comment]
Thank you !! You know if you could come back into this project ? Or is it to old ?

**Comment by erwincoumans** [comment]
Better ask Rama, he is the original author:
https://github.com/ramakarl/fluids3
I only added cmake support.

**Pull request merged**
